spring.application.name=subscription-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.client.id=${GOOGLE_CLIENT_ID}

jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER:subtrak-api}
jwt.audience=${JWT_AUDIENCE:subtrak-web}

app.sendgrid.apiKey=${SENDGRID_API_KEY}
app.sendgrid.fromEmail=${SENDGRID_FROM_EMAIL}
app.sendgrid.fromName=${SENDGRID_FROM_NAME}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

app.frontend.url=https://subtrak-sable.vercel.app
